[OPP-1327] legger til appdynamics støtte
navikt/henvendelsesarkiv-2 pull request #34
Opened 2021-02-18 12:58 UTC by olofab

2021-02-19 07:30 UTC, nutgaard requested changes
Java gjorde en god del endringer i java9, så tror kanskje ikke appen blir så glad av at vi bumper den til java11. :( 

Appd-agent er også oppdatert i java8 imaget, så det burde holde å bare gjøre en "redeploy" av denne appen.

2021-02-19 07:30 UTC, nutgaard commented on Dockerfile
> +FROM navikt/java:11-appdynamics
Tror jeg ville holde denne på java 8, siden vi ikke vet hvordan appen oppfører seg med java11

2021-02-19 10:42 UTC, olofab commented on Dockerfile
> +FROM navikt/java:11-appdynamics
Lurt lurt! Endrer tilbake!

2021-02-22 10:41 UTC, nutgaard approved these changes

2021-02-23 11:14 UTC, merged